// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceApotheke.API.Data;

#nullable disable

namespace ServiceApotheke.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260715123522_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.AtmBillingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ConsentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfService")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<string>("ReportPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sonderkennzeichen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConsentId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("AtmBillingRecords");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.ConsentAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HealthInsuranceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HealthInsuranceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IkNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsWwsExportGranted")
                        .HasColumnType("boolean");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("SignatureBlob")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("SignedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("ConsentAgreements");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.KioskTerminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("KioskTerminals");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.SessionTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("SessionTelemetries");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Consumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BgbWaiverAcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasAcceptedBgbWaiver")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Consumers");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DevicePlatform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PharmacistId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Neujahrstag",
                            StateCode = "DE"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Karfreitag",
                            StateCode = "DE"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ostermontag",
                            StateCode = "DE"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tag der Arbeit",
                            StateCode = "DE"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Christi Himmelfahrt",
                            StateCode = "DE"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pfingstmontag",
                            StateCode = "DE"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tag der Deutschen Einheit",
                            StateCode = "DE"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1. Weihnachtstag",
                            StateCode = "DE"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2026, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2. Weihnachtstag",
                            StateCode = "DE"
                        });
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.InternalShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("EscrowStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEmergencyDuty")
                        .HasColumnType("boolean");

                    b.Property<int>("PharmacyEmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<string>("RateNegotiatedBy")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text");

                    b.Property<string>("StripeTransferId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyEmployeeId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("InternalShifts");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PdfFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimesheetId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("JobPostId")
                        .HasColumnType("integer");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimesheetPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonForVacancy")
                        .HasColumnType("text");

                    b.Property<string>("RequiredQualifications")
                        .HasColumnType("text");

                    b.Property<string>("RequiredWws")
                        .HasColumnType("text");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("numeric");

                    b.Property<string>("ShiftDetails")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.MobileRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("PharmacistId");

                    b.ToTable("MobileRefreshTokens");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CiphertextBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IvBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.PdlDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BillingAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PdlServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PdlServiceId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("PdlDocuments");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.PdlService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiAnalysisResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("BilledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PerformedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PdlServices");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprobationCountry")
                        .HasColumnType("text");

                    b.Property<string>("ApprobationDocumentPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ApprobationNumber")
                        .HasColumnType("text");

                    b.Property<string>("AvailabilityType")
                        .HasColumnType("text");

                    b.Property<int>("AvailableDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("BillingModel")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryOfLicense")
                        .HasColumnType("text");

                    b.Property<string>("CvDocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EmergencyServiceWillingness")
                        .HasColumnType("boolean");

                    b.Property<string>("ExperienceYears")
                        .HasColumnType("text");

                    b.Property<string>("FeeModel")
                        .HasColumnType("text");

                    b.Property<string>("FreelanceContractDocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("FreelanceContractStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("GdprAnonymizedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HasApprobation")
                        .HasColumnType("boolean");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdCardDocumentPath")
                        .HasColumnType("text");

                    b.Property<bool>("IsApprobationVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFreelancerConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKycVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVatRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LiabilityInsuranceDocumentPath")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxDistanceKm")
                        .HasColumnType("integer");

                    b.Property<string>("Mobility")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredContactMethod")
                        .HasColumnType("text");

                    b.Property<string>("PreferredStates")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("text");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RadiusKm")
                        .HasColumnType("integer");

                    b.Property<int>("SessionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ShortNoticeAvailability")
                        .HasColumnType("text");

                    b.Property<string>("SoftwareExperience")
                        .HasColumnType("text");

                    b.Property<string>("Specialties")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeConnectAccountId")
                        .HasColumnType("text");

                    b.Property<string>("TaxId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TravelCostModel")
                        .HasColumnType("text");

                    b.Property<string>("TravelExpenses")
                        .HasColumnType("text");

                    b.Property<string>("TravelWillingness")
                        .HasColumnType("text");

                    b.Property<string>("UstIdValidationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VatSubject")
                        .HasColumnType("text");

                    b.Property<bool>("WeekendWillingness")
                        .HasColumnType("boolean");

                    b.Property<string>("WwsProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Pharmacists");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacistFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ActualPauseMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("BtmComplianceRating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CriticalIncidents")
                        .HasColumnType("text");

                    b.Property<string>("Improvements")
                        .HasColumnType("text");

                    b.Property<int>("JobPostId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrganizationRating")
                        .HasColumnType("integer");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("integer");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("integer");

                    b.Property<string>("Positives")
                        .HasColumnType("text");

                    b.Property<int?>("PrivacyRating")
                        .HasColumnType("integer");

                    b.Property<string>("RelevantAreas")
                        .HasColumnType("text");

                    b.Property<int?>("SupportRating")
                        .HasColumnType("integer");

                    b.Property<bool>("TimesheetConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("WorkloadLevel")
                        .HasColumnType("text");

                    b.Property<int?>("WorkspacePrepRating")
                        .HasColumnType("integer");

                    b.Property<string>("WouldWorkAgain")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("PharmacistFeedbacks");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccommodationProvided")
                        .HasColumnType("text");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BetriebserlaubnisNumber")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataProcessingAgreementSignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FocusAreas")
                        .HasColumnType("text");

                    b.Property<string>("FreelanceContractDocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("FreelanceContractStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GdprAnonymizedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InvoiceBillingPossible")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTelepharmacyConsentGranted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("ParkingAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PharmacyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SessionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SoftwareSystem")
                        .HasColumnType("text");

                    b.Property<string>("StaffSupport")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TargetHourlyRate")
                        .HasColumnType("numeric");

                    b.Property<string>("TelepharmacyConsentDocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("UstIdNr")
                        .HasColumnType("text");

                    b.Property<string>("UstIdValidationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyName");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacyEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("PharmacyEmployees");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacyFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccuracyRating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ActualPauseMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CommunicationRating")
                        .HasColumnType("integer");

                    b.Property<int?>("CompetenceRating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Improvements")
                        .HasColumnType("text");

                    b.Property<int?>("IndependenceRating")
                        .HasColumnType("integer");

                    b.Property<int>("JobPostId")
                        .HasColumnType("integer");

                    b.Property<string>("NextDemand")
                        .HasColumnType("text");

                    b.Property<string>("OnboardingRequired")
                        .HasColumnType("text");

                    b.Property<string>("OverallGrade")
                        .HasColumnType("text");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("integer");

                    b.Property<string>("Positives")
                        .HasColumnType("text");

                    b.Property<string>("Punctuality")
                        .HasColumnType("text");

                    b.Property<int?>("StressManagementRating")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamworkRating")
                        .HasColumnType("integer");

                    b.Property<string>("WouldHireAgain")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("PharmacyFeedbacks");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacyRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PLZ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("pharmacy_registry");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.SaturdayRotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("TeamId");

                    b.ToTable("SaturdayRotations");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.SaturdayRotationTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PharmacistIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("SaturdayRotationTeams");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.TemperatureLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("boolean");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("TemperatureLogs");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccommodationCosts")
                        .HasColumnType("numeric");

                    b.Property<TimeSpan>("ActualEndTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("ActualStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("ActualStartTime")
                        .HasColumnType("interval");

                    b.Property<string>("DigitalSignatureHash")
                        .HasColumnType("text");

                    b.Property<string>("DisputeReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DisputedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimesheetPath")
                        .HasColumnType("text");

                    b.Property<decimal>("TravelCosts")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.AtmBillingRecord", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.ATM.ConsentAgreement", "ConsentAgreement")
                        .WithMany()
                        .HasForeignKey("ConsentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsentAgreement");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.ConsentAgreement", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.KioskTerminal", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.SessionTelemetry", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.DeviceToken", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacist", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.InternalShift", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.PharmacyEmployee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("PharmacyEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Invoice", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Timesheet", "Timesheet")
                        .WithMany()
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobApplication", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.JobPost", "JobPost")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacist", "Pharmacist")
                        .WithMany("JobApplications")
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobPost", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany("JobPosts")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.MobileRefreshToken", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacist", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.Patient", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany("Patients")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.PdlDocument", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.PDL.Patient", "Patient")
                        .WithMany("PdlDocuments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.PDL.PdlService", "PdlService")
                        .WithMany()
                        .HasForeignKey("PdlServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany("PdlDocuments")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PdlService");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.PdlService", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.PDL.Patient", "Patient")
                        .WithMany("PdlServices")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacistFeedback", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacist", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacyEmployee", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacyFeedback", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacist", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.SaturdayRotation", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.SaturdayRotationTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.SaturdayRotationTeam", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.TemperatureLog", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany("TemperatureLogs")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Timesheet", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobPost", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.Patient", b =>
                {
                    b.Navigation("PdlDocuments");

                    b.Navigation("PdlServices");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacist", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacy", b =>
                {
                    b.Navigation("JobPosts");

                    b.Navigation("Patients");

                    b.Navigation("PdlDocuments");

                    b.Navigation("TemperatureLogs");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacyEmployee", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
