// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceApotheke.API.Data;

#nullable disable

namespace ServiceApotheke.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260620112636_InitialCleanState")]
    partial class InitialCleanState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ServiceApotheke.API.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesheetId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimesheetPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accommodation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BillingByInvoice")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FocusAreas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ParkingAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprobationCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprobationDocumentPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailabilityType")
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailableDaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CvDocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmergencyServiceWillingness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExperienceYears")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeeModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GdprAnonymizedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasApprobation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCardDocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsKycVerified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LiabilityInsuranceDocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxDistanceKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mobility")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredContactMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredStates")
                        .HasColumnType("TEXT");

                    b.Property<int>("RadiusKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortNoticeAvailability")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareExperience")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialties")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TermsAcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelExpenses")
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelWillingness")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatSubject")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WeekendWillingness")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Pharmacists");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacistFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BtmProcessScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriticalIncidents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DataProtectionScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnboardingScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverallScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositiveAspects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkloadHV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkloadRecipe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkspaceSetupScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PharmacistFeedbacks");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccommodationProvided")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataProcessingAgreementSignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("FocusAreas")
                        .HasColumnType("TEXT");

                    b.Property<string>("GdprAnonymizedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InvoiceBillingPossible")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ParkingAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PharmacyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffSupport")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetHourlyRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyName");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacyFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualEndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualStartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarefulnessScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImprovementAspects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IndependenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverallScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositiveAspects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StressHandlingScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamworkScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WouldBookAgain")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PharmacyFeedbacks");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccommodationCosts")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ActualEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ActualStartTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TravelCosts")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Invoice", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Timesheet", "Timesheet")
                        .WithMany()
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobApplication", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.JobPost", "JobPost")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacist", "Pharmacist")
                        .WithMany("JobApplications")
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobPost", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany("JobPosts")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Timesheet", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobPost", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacist", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacy", b =>
                {
                    b.Navigation("JobPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
