// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceApotheke.API.Data;

#nullable disable

namespace ServiceApotheke.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260705130455_AddUtmTrackingToPharmacy")]
    partial class AddUtmTrackingToPharmacy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.AtmBillingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ConsentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfService")
                        .HasColumnType("TEXT");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sonderkennzeichen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsentId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("AtmBillingRecords");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.ConsentAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthInsuranceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthInsuranceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IkNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SignatureBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("SignedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("ConsentAgreements");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.KioskTerminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("KioskTerminals");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.SessionTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("SessionTelemetries");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesheetId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimesheetPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonForVacancy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredQualifications")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredWws")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Geburt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEligibleForAmts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KdnNr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.PdlDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BillingAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PdlServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PdlServiceId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("PdlDocuments");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.PdlService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiAnalysisResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BilledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PerformedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PdlServices");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprobationCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprobationDocumentPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailabilityType")
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailableDaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryOfLicense")
                        .HasColumnType("TEXT");

                    b.Property<string>("CvDocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmergencyServiceWillingness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExperienceYears")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeeModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GdprAnonymizedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasApprobation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCardDocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsKycVerified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVatRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LiabilityInsuranceDocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxDistanceKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mobility")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredContactMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredStates")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RadiusKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortNoticeAvailability")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareExperience")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialties")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TermsAcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelCostModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelExpenses")
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelWillingness")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatSubject")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WeekendWillingness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WwsProficiency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Pharmacists");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacistFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActualPauseMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BtmComplianceRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriticalIncidents")
                        .HasColumnType("TEXT");

                    b.Property<string>("Improvements")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Positives")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrivacyRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelevantAreas")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupportRating")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TimesheetConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkloadLevel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkspacePrepRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WouldWorkAgain")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("PharmacistFeedbacks");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccommodationProvided")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataProcessingAgreementSignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("FocusAreas")
                        .HasColumnType("TEXT");

                    b.Property<string>("GdprAnonymizedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InvoiceBillingPossible")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("ParkingAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PharmacyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffSupport")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetHourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyName");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacyFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccuracyRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActualPauseMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommunicationRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompetenceRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Improvements")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndependenceRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobPostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextDemand")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnboardingRequired")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverallGrade")
                        .HasColumnType("TEXT");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Positives")
                        .HasColumnType("TEXT");

                    b.Property<string>("Punctuality")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StressManagementRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamworkRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WouldHireAgain")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("PharmacyFeedbacks");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.TemperatureLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("TemperatureLogs");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccommodationCosts")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ActualEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ActualStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisputedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TravelCosts")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.AtmBillingRecord", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.ATM.ConsentAgreement", "ConsentAgreement")
                        .WithMany()
                        .HasForeignKey("ConsentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsentAgreement");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.ConsentAgreement", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.KioskTerminal", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.ATM.SessionTelemetry", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Invoice", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Timesheet", "Timesheet")
                        .WithMany()
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobApplication", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.JobPost", "JobPost")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacist", "Pharmacist")
                        .WithMany("JobApplications")
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobPost", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany("JobPosts")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.Patient", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany("Patients")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.PdlDocument", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.PDL.Patient", "Patient")
                        .WithMany("PdlDocuments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.PDL.PdlService", "PdlService")
                        .WithMany()
                        .HasForeignKey("PdlServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany("PdlDocuments")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PdlService");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.PdlService", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.PDL.Patient", "Patient")
                        .WithMany("PdlServices")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacistFeedback", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacist", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PharmacyFeedback", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceApotheke.API.Models.Pharmacist", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.TemperatureLog", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.Pharmacy", "Pharmacy")
                        .WithMany("TemperatureLogs")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Timesheet", b =>
                {
                    b.HasOne("ServiceApotheke.API.Models.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.JobPost", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.PDL.Patient", b =>
                {
                    b.Navigation("PdlDocuments");

                    b.Navigation("PdlServices");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacist", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("ServiceApotheke.API.Models.Pharmacy", b =>
                {
                    b.Navigation("JobPosts");

                    b.Navigation("Patients");

                    b.Navigation("PdlDocuments");

                    b.Navigation("TemperatureLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
