-- Session Telemetry

CREATE TABLE IF NOT EXISTS session_telemetry (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL, -- UUID generated by frontend (Standby.tsx)
    pharmacy_id UUID NOT NULL REFERENCES pharmacies(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- 'SESSION_STARTED', 'STEP_CONSENT', 'STEP_SERVICE', 'STEP_TRIAGE', 'SESSION_ABORTED', 'SESSION_COMPLETED'
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for faster aggregation by pharmacy and date
CREATE INDEX IF NOT EXISTS idx_session_telemetry_pharmacy_created ON session_telemetry(pharmacy_id, created_at);
CREATE INDEX IF NOT EXISTS idx_session_telemetry_session_id ON session_telemetry(session_id);

-- RLS
ALTER TABLE session_telemetry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacists can view their own telemetry"
    ON session_telemetry FOR SELECT
    USING (auth.uid() = pharmacy_id);

-- API Server handles inserts via service_role.
